2025-03-11 10:33:27,277 INFO    MainThread:2792 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-11 10:33:27,277 INFO    MainThread:2792 [wandb_setup.py:_flush():67] Configure stats pid to 2792
2025-03-11 10:33:27,277 INFO    MainThread:2792 [wandb_setup.py:_flush():67] Loading settings from /root/.config/wandb/settings
2025-03-11 10:33:27,277 INFO    MainThread:2792 [wandb_setup.py:_flush():67] Loading settings from /home/duckietown_rl_course/duckiesim/rl/wandb/settings
2025-03-11 10:33:27,277 INFO    MainThread:2792 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-11 10:33:27,277 INFO    MainThread:2792 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/duckietown_rl_course/duckiesim/rl/wandb/run-20250311_103327-o36q3px2/logs/debug.log
2025-03-11 10:33:27,277 INFO    MainThread:2792 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/duckietown_rl_course/duckiesim/rl/wandb/run-20250311_103327-o36q3px2/logs/debug-internal.log
2025-03-11 10:33:27,278 INFO    MainThread:2792 [wandb_init.py:init():761] calling init triggers
2025-03-11 10:33:27,278 INFO    MainThread:2792 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'exp_name': 'ppo', 'seed': 1, 'torch_deterministic': True, 'cuda': True, 'track': True, 'wandb_project_name': 'DuckieTownRL', 'wandb_entity': None, 'capture_video': False, 'env_id': 'DuckietownDiscrete-v0', 'total_timesteps': 10000000, 'learning_rate': 0.00025, 'num_envs': 1, 'num_steps': 2048, 'anneal_lr': True, 'gamma': 0.99, 'gae_lambda': 0.95, 'num_minibatches': 4, 'update_epochs': 4, 'norm_adv': True, 'clip_coef': 0.1, 'clip_vloss': True, 'ent_coef': 0.01, 'vf_coef': 0.5, 'max_grad_norm': 0.5, 'target_kl': None, 'batch_size': 2048, 'minibatch_size': 512, 'num_iterations': 4882, '_wandb': {'code_path': 'code/duckiesim/rl/ppo.py'}}
2025-03-11 10:33:27,278 INFO    MainThread:2792 [wandb_init.py:init():784] starting backend
2025-03-11 10:33:27,278 INFO    MainThread:2792 [wandb_init.py:init():788] sending inform_init request
2025-03-11 10:33:27,307 INFO    MainThread:2792 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-11 10:33:27,308 INFO    MainThread:2792 [wandb_init.py:init():803] backend started and connected
2025-03-11 10:33:27,312 INFO    MainThread:2792 [wandb_init.py:init():896] updated telemetry
2025-03-11 10:33:27,342 INFO    MainThread:2792 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-11 10:33:27,731 INFO    MainThread:2792 [wandb_init.py:init():995] starting run threads in backend
2025-03-11 10:33:27,860 INFO    MainThread:2792 [wandb_run.py:_console_start():2377] atexit reg
2025-03-11 10:33:27,861 INFO    MainThread:2792 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-11 10:33:27,861 INFO    MainThread:2792 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-11 10:33:27,861 INFO    MainThread:2792 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-11 10:33:27,863 INFO    MainThread:2792 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-11 10:43:24,698 WARNING MsgRouterThr:2792 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/opt/conda/envs/duckietownrl/lib/python3.8/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/opt/conda/envs/duckietownrl/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/opt/conda/envs/duckietownrl/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/duckietownrl/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/opt/conda/envs/duckietownrl/lib/python3.8/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-11 10:43:24,699 INFO    MsgRouterThr:2792 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
